# Generated by Django 4.0.4 on 2022-09-11 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=500)),
                ('course_image', models.ImageField(upload_to='course_images')),
                ('course_duration', models.CharField(blank=True, max_length=20, null=True)),
                ('class_size', models.CharField(max_length=20)),
                ('class_durations', models.CharField(max_length=20)),
                ('course_descriptions', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherName', models.CharField(blank=True, max_length=700)),
                ('TeacherImage', models.ImageField(upload_to='teacherprofile')),
                ('TeacherDesignations', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairman_name', models.CharField(blank=True, max_length=100, null=True)),
                ('welcome_message', models.TextField(blank=True, max_length=5000, null=True)),
                ('chairman_image', models.ImageField(upload_to='chairman')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacebookLink', models.URLField(blank=True, null=True)),
                ('TwitterLink', models.URLField(blank=True, null=True)),
                ('TeacherName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeacherDetail', to='main_app.teachersection')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_instructor', models.CharField(blank=True, max_length=200, null=True)),
                ('instructor_designation', models.CharField(max_length=900)),
                ('instructor_fb', models.URLField(blank=True, null=True)),
                ('instructor_twitter', models.URLField(blank=True, null=True)),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseDetails', to='main_app.course')),
            ],
        ),
    ]
