# Generated by Django 3.2.5 on 2022-09-16 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('about_description', models.TextField(blank=True, max_length=5000, null=True)),
                ('about_image', models.ImageField(upload_to='chairman')),
            ],
        ),
        migrations.CreateModel(
            name='ChairmanSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairman_name', models.CharField(blank=True, max_length=100, null=True)),
                ('welcome_message', models.TextField(blank=True, max_length=5000, null=True)),
                ('chairman_image', models.ImageField(upload_to='chairman')),
            ],
        ),
        migrations.CreateModel(
            name='Facilites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('image', models.ImageField(upload_to='facilites')),
                ('heading', models.CharField(blank=True, max_length=5000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=500, null=True)),
                ('sub_heading', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherName', models.CharField(blank=True, max_length=700)),
                ('TeacherImage', models.ImageField(upload_to='teacherprofile')),
                ('TeacherDesignations', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacebookLink', models.URLField(blank=True, null=True)),
                ('TwitterLink', models.URLField(blank=True, null=True)),
                ('TeacherName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeacherDetail', to='main_app.teachersection')),
            ],
        ),
        migrations.CreateModel(
            name='FacilitiesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField(blank=True, max_length=7000, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=500, null=True)),
                ('teacher_designation', models.CharField(blank=True, max_length=500, null=True)),
                ('fb_link', models.URLField(blank=True, max_length=500, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=500, null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FacilitiesDetails', to='main_app.facilites')),
            ],
        ),
    ]
