# Generated by Django 4.0.4 on 2022-09-12 23:04

from django.db import migrations, models
import tkinter.tix


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcome',
            name='descriptions',
            field=models.TextField(blank=True, max_length=1000, null=tkinter.tix.Tree),
        ),
    ]
