# Generated by Django 3.2.5 on 2022-09-16 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(blank=True, max_length=100, null=True)),
                ('event_date', models.DateTimeField()),
                ('event_time', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_descriptions', models.TextField(blank=True, max_length=7000, null=True)),
                ('event_pdf', models.FileField(upload_to='department_files')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EventDetails', to='main_app.event')),
            ],
        ),
    ]
