# Generated by Django 4.0.4 on 2022-09-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='course_description',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
