# Generated by Django 4.0.4 on 2022-09-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_coursedetail_course_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(blank=True, max_length=350, null=True)),
                ('image', models.ImageField(upload_to='chairman')),
                ('sub_heading', models.TextField(blank=True, max_length=6000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='course_title',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseDetail',
        ),
    ]
