# Generated by Django 3.2.5 on 2022-09-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_event_eventdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='event_main_speaker',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
    ]
