# Generated by Django 4.0.4 on 2022-09-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_facilites_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('about_description', models.TextField(blank=True, max_length=5000, null=True)),
                ('about_image', models.ImageField(upload_to='chairman')),
            ],
        ),
    ]
