# Generated by Django 4.0.4 on 2022-09-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_home_remove_coursedetail_course_title_delete_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='Heading',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image',
        ),
        migrations.AddField(
            model_name='home',
            name='heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
