# Generated by Django 4.0.4 on 2022-09-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_coursedetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseDetails',
            new_name='CourseDetail',
        ),
    ]
