# Generated by Django 3.2.5 on 2022-09-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_eventdetails_event_main_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default=1, upload_to='event'),
            preserve_default=False,
        ),
    ]
