# Generated by Django 4.0.4 on 2022-09-12 18:58

from django.db import migrations, models
import tkinter.tix


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_home_heading_remove_home_image_home_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, max_length=5000, null=True)),
                ('desricptions', models.TextField(blank=True, max_length=10000, null=tkinter.tix.Tree)),
            ],
        ),
    ]
