# Generated by Django 3.2.5 on 2022-09-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_event_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdetails',
            old_name='title',
            new_name='event_title',
        ),
    ]
