# Generated by Django 4.0.4 on 2022-09-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_coursedetail_instructor_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='instructor_fb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='instructor_twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
