# Generated by Django 4.0.4 on 2022-09-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_welcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('image', models.ImageField(upload_to='facilites')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
