# Generated by Django 4.0.4 on 2022-09-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_coursedetail_instructor_fb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherName', models.CharField(blank=True, max_length=700)),
                ('TeacherDesignations', models.CharField(max_length=400, null=True)),
                ('Descriptions', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
