# Generated by Django 4.0.4 on 2022-09-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_facilites'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilites',
            name='heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
