# Generated by Django 3.2.5 on 2022-09-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_publications_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('image', models.ImageField(upload_to='chairman')),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
