# Generated by Django 4.0.4 on 2022-09-05 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_teachersection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersection',
            name='Descriptions',
        ),
        migrations.AddField(
            model_name='teachersection',
            name='TeacherImage',
            field=models.ImageField(default=1, upload_to='teacherprofile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TeacherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeacherDetail', to='main_app.teachersection')),
            ],
        ),
    ]
