# Generated by Django 3.2.5 on 2022-09-17 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_research'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=120, null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ResearchDetail', to='main_app.research')),
            ],
        ),
    ]
