# Generated by Django 3.2.5 on 2022-09-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_researchdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='descriptions',
            field=models.TextField(blank=True, max_length=9000, null=True),
        ),
    ]
