# Generated by Django 3.2.5 on 2022-09-20 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_research_descriptions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Welcome',
        ),
    ]
