# Generated by Django 3.2.5 on 2022-09-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_delete_welcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_description',
            field=models.TextField(blank=True, max_length=40000, null=True),
        ),
    ]
